name: Generate Doxygen Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Upload Doxygen documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: html/
